### PR TITLE
git-archive replaces zip command in entrypoint docker shell

### PR DESCRIPTION
**Pull request by rogerlward**
I love your script!  I saw a todo and thought I'd offer some help - wanted to learn the basics of a factorio mod and along the way like to fix up things and learn.  

Short story is I've tested this and was able to push 1.0.2 of RespawnStarterArmor using git-archive (i deleted it, because it was a minor/test revision, but it works!).

I rebased to incorporate your commits before submitting the PR (the tests were done after rebase).  

Obligatory works on my box.  Let me know if you want any help with it further.

### CODE REVIEW

**Review by rogerlward — COMMENTED** [review]
just re-reading the PR and noticed in entrypoint.sh i used INFO_VERSION and TAG separately in the git archive command, even though they have been tested to be equal at this point.  I did this because of the way I was thinking logically about each piece - $TAG in an entirely different case might not equal $INFO_VERSION but for factorio INFO_VERSION is what should be used regardless of TAG.  

I worked a couple of places that had issues once and little things like this help later people understand which piece of info goes where.  Maybe I could have added a comment in the file?

**Comment by rogerlward** [comment]
tried to tag a PR from another repo - but I created a .gitattributes file that will hide the .github dir (that the zip command already did) if you push this script.  Let me know if that is helpful and i'll do the same for the others i see publicly.

https://github.com/shanemadden/factorio-logistic-cargo-wagon/pull/11

**Comment by shanemadden** [comment]
Looks good, thanks for doing this!

**Comment by rogerlward** [comment]
No problem!

**Pull request merged**
